-- Enable RLS (Row Level Security) is recommended, but for MVP we start simple.

-- 1. Users/Profiles Table (Combines Admin, Manager, Collaborator)
-- Note: Supabase Auth handles authentication, but we need a public profile table 
-- to store app-specific fields like 'role', 'employee_number', etc.
create type user_role as enum ('ADMIN', 'MANAGER', 'COLLABORATOR');
create type shift_type as enum ('MATUTINO', 'VESPERTINO');

create table public.profiles (
  id uuid references auth.users not null primary key, -- Linked to Supabase Auth
  email text,
  name text not null,
  employee_number text unique not null,
  role user_role not null default 'COLLABORATOR',
  
  -- Specific to Collaborators
  role_title text,
  shift shift_type,
  avatar_initials text,
  manager_id uuid references public.profiles(id), -- Hierarchy
  
  created_at timestamptz default now()
);

-- 2. Branch Configuration (One per Manager)
create table public.branch_configs (
  id bigint generated by default as identity primary key,
  manager_id uuid references public.profiles(id) not null,
  name text not null,
  ceco text,
  region text,
  territory text,
  created_at timestamptz default now()
);

-- 3. Shift Configuration
create table public.shift_configs (
  id bigint generated by default as identity primary key,
  manager_id uuid references public.profiles(id) not null,
  
  matutino_start time not null default '08:00',
  matutino_end time not null default '15:00',
  
  vespertino_start time not null default '12:00',
  vespertino_end time not null default '20:00'
);

-- 4. Activity Definitions (The "Types" of activities a manager can assign)
create table public.activity_definitions (
  id bigint generated by default as identity primary key,
  manager_id uuid references public.profiles(id) not null,
  name text not null,
  created_at timestamptz default now()
);

-- 5. Activities (The actual daily records)
create table public.activities (
  id uuid default gen_random_uuid() primary key,
  collaborator_id uuid references public.profiles(id) not null,
  
  day_of_week int not null, -- 0-6
  time_start time not null,
  time_end time not null,
  description text not null,
  
  is_completed boolean default false,
  completed_at timestamptz,
  
  created_at timestamptz default now()
);

-- 6. Emergency Contacts
create table public.emergency_contacts (
  id uuid default gen_random_uuid() primary key,
  manager_id uuid references public.profiles(id) not null,
  name text not null,
  phone text not null
);

-- Row Level Security (RLS) Basics
alter table profiles enable row level security;
alter table activities enable row level security;

-- Policy: Users can read their own profile
create policy "Public profiles are viewable by everyone" 
on profiles for select using ( true );

-- Policy: Users can update their own profile
create policy "Users can update own profile" 
on profiles for update using ( auth.uid() = id );
